name: Deploy snapshots to self

on:
  workflow_call:
    secrets:
      OUTLINE_INSTANCE_URL:
        required: true
      OUTLINE_API_KEY:
        required: true

jobs:
  deploy_snapshots_to_self:
    runs-on: ubuntu-latest
    container: ghcr.io/zensharp/outline-mirror:latest
    steps:
      - name: Generate snapshots
        run: |
          export OUTLINE_INSTANCE_URL=${{ secrets.OUTLINE_INSTANCE_URL }}
          export OUTLINE_API_KEY=${{ secrets.OUTLINE_API_KEY }}
          outline-mirror
      - name: Deploy snapshot (Markdown)
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: mirror/markdown
          FOLDER: export-markdown
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy snapshot (JSON)
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: mirror/json
          FOLDER: export-json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
